import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {filterQuests} from '../src/quest-filters.js';
import {parseQuest} from './quest-parser.mjs';
import {renderRewardSection} from '../src/quest-reward-view.js';
const {quests}=JSON.parse(readFileSync('public/quests/database.json'));
assert(quests.length>100);
assert.equal(new Set(quests.map(q=>q.id)).size,quests.length);
for(const q of quests){assert(q.revision>0);assert(q.title);assert(q.sections.length>0);}
assert.equal(quests.find(q=>q.title==='A Quick Quest').minLevel,1);
assert.equal(quests.find(q=>q.title==='Wyrmsbane Armor Quest').status,'disabled');
const rows=filterQuests(quests,{zone:'Night Harbor',className:'Archer',level:'1',includeUnknown:false});
assert(rows.some(q=>q.title==='Archer Starter Quest (Night Harbor)'));
assert(rows.every(q=>q.zone==='Night Harbor'&&q.minLevel!==null&&q.minLevel<=1&&(q.allClasses||q.classes.includes('Archer'))));
assert(filterQuests(quests,{search:'intricate ale mug'}).some(q=>q.title==='A Quick Quest'));
assert.equal(filterQuests(quests,{search:'no-such-quest-xyz'}).length,0);
assert(filterQuests(quests,{level:'1'}).length>filterQuests(quests,{level:'1',includeUnknown:false}).length);
const missing=parseQuest({pageid:1,title:'Missing',revid:1,text:{'*':'<div class="mw-parser-output"><h2>Walkthrough</h2><p>Unknown</p></div>'},categories:[]});
assert.equal(missing.minLevel,null);assert.equal(missing.allClasses,false);assert.equal(missing.zone,null);
console.log(`Quest parser, dataset and filter checks passed (${quests.length} quests).`);
const {rewardItems}=JSON.parse(readFileSync('public/quests/database.json'));
const archer=quests.find(q=>q.title==='Archer Starter Quest (Night Harbor)');
const reward=archer.sections.find(s=>s.links?.some(l=>l.title==='Steel Talons Bowman Tunic'));
assert(reward);
assert.equal(rewardItems['Steel Talons Bowman Tunic'].stats.ac,'5');
const html=renderRewardSection(reward,rewardItems);
assert(html.includes('href="https://monstersandmemories.miraheze.org/wiki/Steel_Talons_Bowman_Tunic"'));
assert(html.includes('role="tooltip"'));
assert(html.includes('<b>AC</b> 5'));
assert.equal(renderRewardSection({text:'<script>bad</script>',links:[]}), '&lt;script&gt;bad&lt;/script&gt;');
assert(renderRewardSection({text:'Unknown',links:[{label:'Unknown',title:'Unknown',url:'https://monstersandmemories.miraheze.org/wiki/Unknown'}]},{}).includes('No item stats documented'));
for(const q of quests)for(const s of q.sections)for(const l of s.links||[])assert(rewardItems[l.title],`Unresolved reward: ${l.title}`);
console.log('Reward links, stat previews, fallback and escaping checks passed.');
